In [24]:
import pandas as pd

df= pd.read_excel("../Base_de_dados_ligacoes_rodoviarias_e_hidroviarias_2016.xlsx", sheet_name=['Base de dados'])
df2 = df['Base de dados']

In [51]:
dfIGBE = df2.rename(columns={'CODMUNDV_A': 'GeocodOrigem', 'CODMUNDV_B': 'GeocodDestino','VAR05':'PessoasHidro','VAR06':'PessoasRod'})
dfIGBE = dfIGBE.loc[dfIGBE['UF_A'].str.len()<3]
dfIGBE = dfIGBE.loc[dfIGBE['UF_B'].str.len()<3]
dfIGBE['PessoasAnoR'] = dfIGBE['PessoasRod'] * 22 * 52
dfIGBE['PessoasAnoH'] = dfIGBE['PessoasHidro'] * 22 * 52

display(dfIGBE)

,ID,COD_UF_A,UF_A,GeocodOrigem,NOMEMUN_A,COD_UF_B,UF_B,GeocodDestino,NOMEMUN_B,VAR01,...,VAR07,VAR08,VAR09,VAR10,VAR11,VAR12,VAR13,VAR14,PessoasAnoR,PessoasAnoH
0,13026031304260,13,AM,1302603,Manaus,13,AM,1304260,Uarini,Núcleo de Metrópole (Manaus),...,7.5,-60.023335,-3.134691,-65.155346,-2.983609,0.0,Não,0.023148,0.0,8580.0
1,13021081302603,13,AM,1302108,Japurá,13,AM,1302603,Manaus,Centro Local,...,3.0,-66.996903,-1.880845,-60.023335,-3.134691,3.0,Não,0.026620,0.0,3432.0
2,51038095108402,51,MT,5103809,Figueirópolis D'Oeste,51,MT,5108402,Várzea Grande,Centro Local,...,42.0,-58.737825,-15.446135,-56.144664,-15.658065,0.0,Sim,0.028000,48048.0,0.0
3,13000291302603,13,AM,1300029,Alvarães,13,AM,1302603,Manaus,Centro Local,...,7.5,-64.813535,-3.216584,-60.023335,-3.134691,0.0,Não,0.031250,0.0,8580.0
4,13000291301308,13,AM,1300029,Alvarães,13,AM,1301308,Codajás,Centro Local,...,6.0,-64.813535,-3.216584,-62.063430,-3.843046,0.0,Não,0.036232,0.0,6864.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65633,23042362313609,23,CE,2304236,Croatá,23,CE,2313609,Ubajara,Centro Local,...,7.0,-40.909045,-4.414057,-40.907144,-3.848491,0.0,Não,0.066216,8008.0,0.0
65634,35262093537206,35,SP,3526209,Juquitiba,35,SP,3537206,Pedro de Toledo,Integrante de Metrópole (São Paulo),...,7.0,-47.081594,-23.935689,-47.229076,-24.272801,0.0,Não,0.171778,8008.0,0.0
65635,35414064114104,35,SP,3541406,Presidente Prudente,41,PR,4114104,Mandaguaçu,Capital Regional C,...,14.0,-51.386766,-22.122743,-52.094253,-23.342789,0.0,Não,0.136500,16016.0,0.0
65636,41141044114807,41,PR,4114104,Mandaguaçu,41,PR,4114807,Marialva,Centro Local,...,21.0,-52.094253,-23.342789,-51.798057,-23.484759,0.0,Não,0.159500,24024.0,0.0
65637,43202065007208,43,RS,4320206,Seberi,50,MS,5007208,Rio Brilhante,Centro Local,...,2.0,-53.405467,-27.480414,-54.542242,-21.801195,0.0,Não,0.162375,2288.0,0.0

In [45]:
IbgeRod = dfIGBE.loc[:, [ 'GeocodOrigem','UF_A',  'NOMEMUN_A','GeocodDestino', 'UF_B', 'NOMEMUN_B','PessoasRod','PessoasAnoR']]
IbgeHidro = dfIGBE.loc[:, [ 'GeocodOrigem', 'UF_A','NOMEMUN_A', 'GeocodDestino','UF_B', 'NOMEMUN_B','PessoasHidro','PessoasAnoH']]

IbgeRod = IbgeRod.query('PessoasRod != 0')
IbgeHidro = IbgeHidro.query('PessoasHidro != 0')

IbgeRod2 = IbgeRod.copy()

# Renomeie as colunas de origem para destino e vice-versa
IbgeRod2.rename(columns={
    'GeocodOrigem': 'GeocodDestino',
    'UF_A': 'UF_B',
    'NOMEMUN_A': 'NOMEMUN_B',
    'GeocodDestino': 'GeocodOrigem',
    'UF_B': 'UF_A',
    'NOMEMUN_B': 'NOMEMUN_A'
}, inplace=True)

# Concatene o DataFrame original e o DataFrame modificado
IbgeRod = pd.concat([IbgeRod, IbgeRod2], ignore_index=True)

IbgeHidro2 = IbgeHidro.copy()

# Renomeie as colunas de origem para destino e vice-versa
IbgeHidro2.rename(columns={
    'GeocodOrigem': 'GeocodDestino',
    'UF_A': 'UF_B',
    'NOMEMUN_A': 'NOMEMUN_B',
    'GeocodDestino': 'GeocodOrigem',
    'UF_B': 'UF_A',
    'NOMEMUN_B': 'NOMEMUN_A'
}, inplace=True)

# Concatene o DataFrame original e o DataFrame modificado
IbgeHidro = pd.concat([IbgeHidro, IbgeHidro2], ignore_index=True)


display(IbgeRod)
display(IbgeHidro)

,GeocodOrigem,UF_A,NOMEMUN_A,GeocodDestino,UF_B,NOMEMUN_B,PessoasRod,PessoasAnoR
0,5103809,MT,Figueirópolis D'Oeste,5108402,MT,Várzea Grande,42.0,48048.0
1,1501204,PA,Baião,1504604,PA,Mocajuba,68.0,77792.0
2,1502103,PA,Cametá,1504604,PA,Mocajuba,6.0,6864.0
3,2300150,CE,Acarape,2304400,CE,Fortaleza,716.0,819104.0
4,2304400,CE,Fortaleza,2311603,CE,Redenção,645.0,737880.0
...,...,...,...,...,...,...,...,...
130237,2313609,CE,Ubajara,2304236,CE,Croatá,7.0,8008.0
130238,3537206,SP,Pedro de Toledo,3526209,SP,Juquitiba,7.0,8008.0
130239,4114104,PR,Mandaguaçu,3541406,SP,Presidente Prudente,14.0,16016.0
130240,4114807,PR,Marialva,4114104,PR,Mandaguaçu,21.0,24024.0
130241,5007208,MS,Rio Brilhante,4320206,RS,Seberi,2.0,2288.0

,GeocodOrigem,UF_A,NOMEMUN_A,GeocodDestino,UF_B,NOMEMUN_B,PessoasHidro,PessoasAnoH
0,1302603,AM,Manaus,1304260,AM,Uarini,7.50,8580.0
1,1302108,AM,Japurá,1302603,AM,Manaus,3.00,3432.0
2,1300029,AM,Alvarães,1302603,AM,Manaus,7.50,8580.0
3,1300029,AM,Alvarães,1301308,AM,Codajás,6.00,6864.0
4,1300300,AM,Autazes,1300805,AM,Borba,9.00,10296.0
...,...,...,...,...,...,...,...,...
805,1303908,AM,São Paulo de Olivença,1300060,AM,Amaturá,17.75,20306.0
806,1304237,AM,Tonantins,1300060,AM,Amaturá,17.75,20306.0
807,1304302,AM,Urucará,1302009,AM,Itapiranga,84.00,96096.0
808,1303700,AM,Santo Antônio do Içá,1300060,AM,Amaturá,20.75,23738.0
809,1304237,AM,Tonantins,1303700,AM,Santo Antônio do Içá,29.75,34034.0

Duplicar cada linha invertendo origem e destino com mesmo valor de frequencia

In [52]:
IbgeRod.to_csv('IBGE_R.csv', index=True)
IbgeHidro.to_csv('IBGE_H.csv', index=True)

Media IBGE e DNIT

In [47]:
dfDNIT = pd.read_csv("../DNIT.csv")
display(dfDNIT)
IbgeRod = IbgeRod[['GeocodOrigem', 'GeocodDestino', 'NOMEMUN_A', 'UF_A', 'NOMEMUN_B', 'UF_B', 'PessoasRod', 'PessoasAnoR']]
display(IbgeRod)

,GeocodOrigem,GeocodDestino,MOrigem,UFOrigem,MDestino,UFDestino,PessoasAno
0,1100015.0,1100015.0,Alta Floresta D'Oeste,RO,Alta Floresta D'Oeste,RO,289.0
1,1100015.0,1100023.0,Alta Floresta D'Oeste,RO,Ariquemes,RO,8.5
2,1100015.0,1100049.0,Alta Floresta D'Oeste,RO,Cacoal,RO,64224.0
3,1100015.0,1100122.0,Alta Floresta D'Oeste,RO,Ji-Paraná,RO,1732.0
4,1100015.0,1100189.0,Alta Floresta D'Oeste,RO,Pimenta Bueno,RO,4.0
...,...,...,...,...,...,...,...
169656,5300108.0,5221809.0,Brasília,DF,Urutaí,GO,29.0
169657,5300108.0,5222005.0,Brasília,DF,Vianópolis,GO,16.0
169658,5300108.0,5222203.0,Brasília,DF,Vila Boa,GO,123708.0
169659,5300108.0,5222302.0,Brasília,DF,Vila Propício,GO,4.0
169660,5300108.0,5300108.0,Brasília,DF,Brasília,DF,77763.0

,GeocodOrigem,GeocodDestino,NOMEMUN_A,UF_A,NOMEMUN_B,UF_B,PessoasRod,PessoasAnoR
0,5103809,5108402,Figueirópolis D'Oeste,MT,Várzea Grande,MT,42.0,48048.0
1,1501204,1504604,Baião,PA,Mocajuba,PA,68.0,77792.0
2,1502103,1504604,Cametá,PA,Mocajuba,PA,6.0,6864.0
3,2300150,2304400,Acarape,CE,Fortaleza,CE,716.0,819104.0
4,2304400,2311603,Fortaleza,CE,Redenção,CE,645.0,737880.0
...,...,...,...,...,...,...,...,...
130237,2313609,2304236,Ubajara,CE,Croatá,CE,7.0,8008.0
130238,3537206,3526209,Pedro de Toledo,SP,Juquitiba,SP,7.0,8008.0
130239,4114104,3541406,Mandaguaçu,PR,Presidente Prudente,SP,14.0,16016.0
130240,4114807,4114104,Marialva,PR,Mandaguaçu,PR,21.0,24024.0
130241,5007208,4320206,Rio Brilhante,MS,Seberi,RS,2.0,2288.0

In [48]:
IbgeRod.rename(columns={'PessoasAnoR': 'PessoasAno','NOMEMUN_A':'MOrigem','UF_A':'UFOrigem','NOMEMUN_B':'MDestino','UF_B':'UFDestino'}, inplace=True)
#IbgeRod.drop(columns=['PessoasRod'], inplace=True)

display(IbgeRod)
display(dfDNIT)

dfTotal = pd.concat([dfDNIT, IbgeRod], ignore_index=False)
dfTotal = dfTotal.groupby(['GeocodOrigem','GeocodDestino']).agg({'MOrigem':'first','UFOrigem' :'first','MDestino':'first','UFDestino' :'first','PessoasAno':'mean'})

,GeocodOrigem,GeocodDestino,MOrigem,UFOrigem,MDestino,UFDestino,PessoasRod,PessoasAno
0,5103809,5108402,Figueirópolis D'Oeste,MT,Várzea Grande,MT,42.0,48048.0
1,1501204,1504604,Baião,PA,Mocajuba,PA,68.0,77792.0
2,1502103,1504604,Cametá,PA,Mocajuba,PA,6.0,6864.0
3,2300150,2304400,Acarape,CE,Fortaleza,CE,716.0,819104.0
4,2304400,2311603,Fortaleza,CE,Redenção,CE,645.0,737880.0
...,...,...,...,...,...,...,...,...
130237,2313609,2304236,Ubajara,CE,Croatá,CE,7.0,8008.0
130238,3537206,3526209,Pedro de Toledo,SP,Juquitiba,SP,7.0,8008.0
130239,4114104,3541406,Mandaguaçu,PR,Presidente Prudente,SP,14.0,16016.0
130240,4114807,4114104,Marialva,PR,Mandaguaçu,PR,21.0,24024.0
130241,5007208,4320206,Rio Brilhante,MS,Seberi,RS,2.0,2288.0

,GeocodOrigem,GeocodDestino,MOrigem,UFOrigem,MDestino,UFDestino,PessoasAno
0,1100015.0,1100015.0,Alta Floresta D'Oeste,RO,Alta Floresta D'Oeste,RO,289.0
1,1100015.0,1100023.0,Alta Floresta D'Oeste,RO,Ariquemes,RO,8.5
2,1100015.0,1100049.0,Alta Floresta D'Oeste,RO,Cacoal,RO,64224.0
3,1100015.0,1100122.0,Alta Floresta D'Oeste,RO,Ji-Paraná,RO,1732.0
4,1100015.0,1100189.0,Alta Floresta D'Oeste,RO,Pimenta Bueno,RO,4.0
...,...,...,...,...,...,...,...
169656,5300108.0,5221809.0,Brasília,DF,Urutaí,GO,29.0
169657,5300108.0,5222005.0,Brasília,DF,Vianópolis,GO,16.0
169658,5300108.0,5222203.0,Brasília,DF,Vila Boa,GO,123708.0
169659,5300108.0,5222302.0,Brasília,DF,Vila Propício,GO,4.0
169660,5300108.0,5300108.0,Brasília,DF,Brasília,DF,77763.0

In [53]:
display(dfTotal)
dfTotal.to_csv('IBGE_DNIT.csv', index=True)

                                          MOrigem UFOrigem  \
GeocodOrigem GeocodDestino
1100015.0    1100015.0      Alta Floresta D'Oeste       RO
             1100023.0      Alta Floresta D'Oeste       RO
             1100049.0      Alta Floresta D'Oeste       RO
             1100114.0      Alta Floresta D'Oeste       RO
             1100122.0      Alta Floresta D'Oeste       RO
...                                           ...      ...
5300108.0    5221809.0                   Brasília       DF
             5222005.0                   Brasília       DF
             5222203.0                   Brasília       DF
             5222302.0                   Brasília       DF
             5300108.0                   Brasília       DF

                                         MDestino UFDestino  PessoasAno
GeocodOrigem GeocodDestino
1100015.0    1100015.0      Alta Floresta D'Oeste        RO      289.00
             1100023.0                  Ariquemes        RO     4008.25
             1100049.0                     Cacoal        RO    43552.00
             1100114.0                       Jaru        RO     8008.00
             1100122.0                  Ji-Paraná        RO     8874.00
...                                           ...       ...         ...
5300108.0    5221809.0                     Urutaí        GO       29.00
             5222005.0                 Vianópolis        GO    20028.00
             5222203.0                   Vila Boa        GO   123708.00
             5222302.0              Vila Propício        GO    16018.00
             5300108.0                   Brasília        DF    77763.00

[265021 rows x 5 columns]